### ISSUE TITLE
Mywhoosh fit files don't upload average data to Garmin Connect

### ISSUE THREAD

**Issue by EB5TC** [jat255/fit_file_uploader#7] opened 2024-11-11 18:11 UTC
When I send fit file to fit_file_uploader generated from Mywhoosh, power, cadence and pulse average din't appear on the Garmin Connect platform.

**Comment by jat255** [comment] 2024-11-11 18:37
That's not terribly surprising, as I've never used Mywhoosh, and don't really know what their FIT files look like. If you're willing to work on getting it working, I'd be happy to review a PR so this tool would work for Mywhoosh, too

**Comment by EB5TC** [comment] 2024-11-11 19:55
Hello,
Thanks for answer I attached FIT file created by MyWhoosh.
[MyNewActivity-3.8.5.zip](https://github.com/user-attachments/files/17707729/MyNewActivity-3.8.5.zip)

**Comment by jat255** [comment] 2024-11-13 00:45
As I don't use MyWhoosh, I won't work on supporting it directly, but thank you for supplying the file. I'm going to close this issue for now (as it's not a bug, per se), but as I said, am happy to review any contributions related to supporting MyWhoosh FIT files.

**Closed by jat255** 2024-11-13 00:45 UTC
